# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2026 Konstantin Ushakov
"""pyte.tools.fio — run fio from Python tests via pyte.job.

Pure Python over pyte.job's public API; zero shim imports.
fio is resolved from the agent's PATH (the job program is ``"fio"``).
Gate fio tests with ``<req id="FIO"/>`` and the prologue probe.

Pinned mappings (derived from te/lib/tapi_fio/fio.c + fio_internal.c)
======================================================================

**argv mapping** (mirrors tapi_fio fio_binds order, relevant subset):

    --name=<name>
    --filename=<filename>
    --blocksize=<blocksize>
    --iodepth=<iodepth>
    --runtime=<N>s  --time_based     (only when runtime > 0; C emits --runtime=0s
                                     --time_based by default, pyte deliberately
                                     omits both when runtime <= 0)
    --rwmixread=<rwmixread>
    --output-format=json
    --group_reporting
    --direct=1                         (only when direct=True)
    --readwrite=<fio_rwtype>
        rwtype "rand"  → "randrw"
        rwtype "seq"   → "rw"
        rwtype "read"  → "read"
        rwtype "write" → "write"
        rwtype "trim"  → "trim"
        rwtype "randread"  → "randread"
        rwtype "randwrite" → "randwrite"
        rwtype "randtrim"  → "randtrim"
        rwtype "trimwrite" → "trimwrite"
    --ioengine=<ioengine>
        Accepted: sync, psync, vsync, pvsync, pvsync2, libaio, posixaio
    --numjobs=<numjobs>
    --thread
    <extra_args>  (raw, space-split, from user_argument() logic)
    --size=<size_bytes>

**JSON report paths** (from get_report/get_report_io in fio.c):

    jobs[0].read.bw_max           → read.bandwidth.max   (int, KiB/s)
    jobs[0].read.bw_min           → read.bandwidth.min   (int, KiB/s)
    jobs[0].read.bw_mean          → read.bandwidth.mean  (float, KiB/s)
    jobs[0].read.bw_dev           → read.bandwidth.stddev (float, KiB/s)
    jobs[0].read.iops_min         → read.iops.min        (int)
    jobs[0].read.iops_max         → read.iops.max        (int)
    jobs[0].read.iops_mean        → read.iops.mean       (float)
    jobs[0].read.iops_stddev      → read.iops.stddev     (float)
    jobs[0].read.lat_ns.min       → read.latency.min_ns  (int)
    jobs[0].read.lat_ns.max       → read.latency.max_ns  (int)
    jobs[0].read.lat_ns.mean      → read.latency.mean_ns (float)
    jobs[0].read.lat_ns.stddev    → read.latency.stddev_ns (float)
    jobs[0].read.clat_ns.min      → read.clatency.min_ns
    jobs[0].read.clat_ns.max      → read.clatency.max_ns
    jobs[0].read.clat_ns.mean     → read.clatency.mean_ns
    jobs[0].read.clat_ns.stddev   → read.clatency.stddev_ns
    jobs[0].read.clat_ns.percentile."99.000000"  → read.clatency.percentiles.p99_00
    jobs[0].read.clat_ns.percentile."99.500000"  → read.clatency.percentiles.p99_50
    jobs[0].read.clat_ns.percentile."99.900000"  → read.clatency.percentiles.p99_90
    jobs[0].read.clat_ns.percentile."99.950000"  → read.clatency.percentiles.p99_95
    (same for write.*)
    Note: TE's C code truncates the percentile key lookup via ``int / 1000``
    whereas pyte keeps the fraction (deliberate improvement); values may
    differ from C runs when fio's JSON key layout does not align with an
    exact integer boundary.

**MI mapping** (from tapi_fio_mi_report, tapi_fio.c:266-283):

    KBYTE2MBIT(x) = x * 8 / 1000.0   (KiB/s → Mbit/s)

    THROUGHPUT "Read throughput"          MEAN  KBYTE2MBIT(read.bandwidth.mean)   MEBI
    IOPS       "Read iops"                MEAN  read.iops.mean                    PLAIN
    LATENCY    "Read clat 99.00 percentile" PERCENTILE
               read.clatency.percentiles.p99_00 / 1000  MICRO
    THROUGHPUT "Write throughput"         MEAN  KBYTE2MBIT(write.bandwidth.mean)  MEBI
    IOPS       "Write iops"               MEAN  write.iops.mean                   PLAIN
    LATENCY    "Write clat 99.00 percentile" PERCENTILE
               write.clatency.percentiles.p99_00 / 1000 MICRO

**Fixture provenance:**
    lib/pyte/tests/data/fio_sample.json was generated by running fio directly
    on host ``test`` (passwordless SSH):
        fio --name=pyte_sample --filename=/tmp/pyte_fio_sample.dat
            --size=4m --bs=4096 --rw=randrw --rwmixread=50
            --iodepth=4 --runtime=2 --time_based --ioengine=psync
            --output-format=json
    fio version: fio-3.39.  The JSON paths and value types are pinned from
    this real output, not from hand-rolled samples.
"""
from __future__ import annotations

import enum
import json
from contextlib import contextmanager
from dataclasses import dataclass, field
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from pyte.rpc.server import RpcServer

# ---------------------------------------------------------------------------
# Opts
# ---------------------------------------------------------------------------

class RwType(enum.Enum):
    """fio workload type; value is the fio ``--readwrite=`` token."""

    RAND = "randrw"
    SEQ = "rw"
    READ = "read"
    WRITE = "write"
    TRIM = "trim"
    RANDREAD = "randread"
    RANDWRITE = "randwrite"
    RANDTRIM = "randtrim"
    TRIMWRITE = "trimwrite"


class IoEngine(enum.Enum):
    """fio I/O engine; value is the fio ``--ioengine=`` token."""

    SYNC = "sync"
    PSYNC = "psync"
    VSYNC = "vsync"
    PVSYNC = "pvsync"
    PVSYNC2 = "pvsync2"
    LIBAIO = "libaio"
    POSIXAIO = "posixaio"


# Shared helpers (promoted FROM this module to pyte.tools._tool/_units;
# aliased so internal call sites and tests keep their names).
from pyte.tools._tool import coerce_enum as _coerce  # noqa: E402
from pyte.tools._units import parse_size as _parse_size  # noqa: E402


@dataclass(frozen=True)
class Opts:
    """fio job options.

    Parameters
    ----------
    filename:
        Path to the data file (required).
    name:
        Job name (default ``"pyte.fio"``).
    blocksize:
        Block size in bytes (default 4096).
    numjobs:
        Number of parallel jobs (default 1).
    iodepth:
        I/O queue depth (default 1; psync caps at 1).
    runtime:
        Runtime in seconds; 0 means no time limit / run to completion.
        When > 0, ``--runtime=<N>s --time_based`` is added.
    rwmixread:
        Read percentage for mixed workloads (default 50).
    rwtype:
        Workload type; a :class:`RwType` member (e.g. ``RwType.RAND``)
        or the equivalent lowercase name string (e.g. ``"rand"``).
        Valid names: ``rand``, ``seq``, ``read``, ``write``, ``trim``,
        ``randread``, ``randwrite``, ``randtrim``, ``trimwrite``.
    ioengine:
        I/O engine; an :class:`IoEngine` member (e.g. ``IoEngine.PSYNC``)
        or the equivalent lowercase name string (e.g. ``"psync"``).
        Valid names: sync, psync, vsync, pvsync, pvsync2, libaio,
        posixaio.  (rbd is excluded: its extra options are out of
        scope.)
    direct:
        Use O_DIRECT (default False).
    size:
        Data file size as int bytes or string (``"4k"``, ``"16m"``,
        ``"1g"``).  None leaves ``--size`` unset.
    extra_args:
        Raw extra arguments appended at the end (space-split per
        user_argument() logic in fio_internal.c).
    """
    filename: str
    name: str = "pyte.fio"
    blocksize: int = 4096
    numjobs: int = 1
    iodepth: int = 1
    runtime: int = 0
    rwmixread: int = 50
    rwtype: "RwType | str" = RwType.SEQ
    ioengine: "IoEngine | str" = IoEngine.PSYNC
    direct: bool = False
    size: str | int | None = None
    extra_args: list[str] = field(default_factory=list)

    def __post_init__(self) -> None:
        if not self.filename:
            raise ValueError("Opts.filename is required")
        object.__setattr__(self, "rwtype",
                           _coerce(RwType, "rwtype", self.rwtype))
        object.__setattr__(self, "ioengine",
                           _coerce(IoEngine, "ioengine", self.ioengine))
        # Validate size format (parse and discard)
        _parse_size(self.size)

    def to_argv(self) -> list[str]:
        """Build the fio command-line argument list (without argv[0]).

        Mirrors tapi_fio fio_binds order from fio_internal.c.
        """
        argv: list[str] = []
        argv.append(f"--name={self.name}")
        argv.append(f"--filename={self.filename}")
        argv.append(f"--blocksize={self.blocksize}")
        argv.append(f"--iodepth={self.iodepth}")
        if self.runtime > 0:
            argv.append(f"--runtime={self.runtime}s")
            argv.append("--time_based")
        argv.append(f"--rwmixread={self.rwmixread}")
        argv.append("--output-format=json")
        argv.append("--group_reporting")
        if self.direct:
            argv.append("--direct=1")
        argv.append(f"--readwrite={self.rwtype.value}")
        argv.append(f"--ioengine={self.ioengine.value}")
        argv.append(f"--numjobs={self.numjobs}")
        argv.append("--thread")
        # user_argument: space-split extra args appended verbatim
        for arg in self.extra_args:
            argv.extend(arg.split())
        size_bytes = _parse_size(self.size)
        if size_bytes is not None:
            argv.append(f"--size={size_bytes}")
        return argv


# ---------------------------------------------------------------------------
# Report dataclasses
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class Percentiles:
    """clat percentile values (nanoseconds)."""
    p99_00: int
    p99_50: int
    p99_90: int
    p99_95: int


@dataclass(frozen=True)
class Lat:
    """lat_ns stats."""
    min_ns: int
    max_ns: int
    mean_ns: float
    stddev_ns: float


@dataclass(frozen=True)
class Clat:
    """clat_ns stats."""
    min_ns: int
    max_ns: int
    mean_ns: float
    stddev_ns: float
    percentiles: Percentiles


@dataclass(frozen=True)
class Bw:
    """Bandwidth stats (KiB/s)."""
    min: int
    max: int
    mean: float
    stddev: float


@dataclass(frozen=True)
class Iops:
    """IOPS stats."""
    min: int
    max: int
    mean: float
    stddev: float


@dataclass(frozen=True)
class IoStats:
    """Combined I/O stats for one direction (read or write)."""
    bandwidth: Bw
    iops: Iops
    latency: Lat
    clatency: Clat


@dataclass(frozen=True)
class Report:
    """Parsed fio JSON report: read and write stats from jobs[0]."""
    read: IoStats
    write: IoStats


# ---------------------------------------------------------------------------
# Parser
# ---------------------------------------------------------------------------

def _parse_bw(j: dict) -> Bw:
    return Bw(
        min=int(j["bw_min"]),
        max=int(j["bw_max"]),
        mean=float(j["bw_mean"]),
        stddev=float(j["bw_dev"]),
    )


def _parse_iops(j: dict) -> Iops:
    return Iops(
        min=int(j["iops_min"]),
        max=int(j["iops_max"]),
        mean=float(j["iops_mean"]),
        stddev=float(j["iops_stddev"]),
    )


def _parse_lat(j: dict) -> Lat:
    return Lat(
        min_ns=int(j["min"]),
        max_ns=int(j["max"]),
        mean_ns=float(j["mean"]),
        stddev_ns=float(j["stddev"]),
    )


def _parse_clat(j: dict) -> Clat:
    perc_obj = j.get("percentile")
    if perc_obj is not None:
        percentiles = Percentiles(
            p99_00=int(perc_obj["99.000000"]),
            p99_50=int(perc_obj["99.500000"]),
            p99_90=int(perc_obj["99.900000"]),
            p99_95=int(perc_obj["99.950000"]),
        )
    else:
        percentiles = Percentiles(p99_00=0, p99_50=0, p99_90=0, p99_95=0)
    return Clat(
        min_ns=int(j["min"]),
        max_ns=int(j["max"]),
        mean_ns=float(j["mean"]),
        stddev_ns=float(j["stddev"]),
        percentiles=percentiles,
    )


def _parse_io(j: dict) -> IoStats:
    return IoStats(
        bandwidth=_parse_bw(j),
        iops=_parse_iops(j),
        latency=_parse_lat(j["lat_ns"]),
        clatency=_parse_clat(j["clat_ns"]),
    )


def _parse_report(obj: dict) -> Report:
    """Parse a fio JSON output dict into a :class:`Report`.

    ``obj`` is the top-level dict (from ``json.loads()`` on fio's
    ``--output-format=json`` output).  Raises ``KeyError`` on missing
    fields or ``ValueError``/``TypeError`` on wrong value types.
    """
    first_job = obj["jobs"][0]
    return Report(
        read=_parse_io(first_job["read"]),
        write=_parse_io(first_job["write"]),
    )


# ---------------------------------------------------------------------------
# Fio: lifecycle class
# ---------------------------------------------------------------------------

class Fio:
    """Lifecycle manager for a running fio job.

    Normally created via :func:`run` which is a context manager.
    All I/O happens over ``pco.job("fio", argv)``; the JSON report
    arrives on stdout.  No shim imports: pure Python over pyte.job.
    """

    def __init__(self, job, stdout_filter):
        self._job = job
        self._stdout_filter = stdout_filter
        self._report: Report | None = None
        self._closed = False

    def wait(self, timeout: float = 120.0) -> Report:
        """Wait for fio to finish, parse JSON, return :class:`Report`.

        Caches the report; subsequent calls return the cached value.
        Raises :exc:`pyte.errors.FioError` on non-zero exit or JSON
        parse failure.
        """
        if self._report is not None:
            return self._report

        from pyte.errors import FioError
        from pyte.job import JobStatus

        status: JobStatus = self._job.wait(timeout=timeout)
        raw = self._stdout_filter.read_all(timeout=timeout)

        if not status.ok:
            raise FioError(
                f"fio exited with {status}; stdout={raw[:200]!r}")
        # fio may emit diagnostic lines (e.g. iodepth capped warnings)
        # to stdout before the JSON block.  Strip any prefix up to the
        # first '{' so json.loads sees only the JSON object.
        json_start = raw.find("{")
        if json_start > 0:
            raw = raw[json_start:]
        try:
            obj = json.loads(raw)
        except json.JSONDecodeError as exc:
            raise FioError(
                f"cannot parse fio JSON output: {exc}; "
                f"stdout={raw[:200]!r}") from exc
        self._report = _parse_report(obj)
        return self._report

    def mi_report(self, tool: str = "fio") -> None:
        """Emit MI measurement artifacts mirroring tapi_fio_mi_report().

        KBYTE2MBIT(x) = x * 8 / 1000.0 (KiB/s → Mbit/s).

        Requires :meth:`wait` to have been called first.
        """
        if self._report is None:
            raise RuntimeError("call wait() before mi_report()")
        from pyte.mi import Aggr, Logger, Meas, Mult

        rep = self._report

        def kbyte2mbit(x: float) -> float:
            return x * 8 / 1000.0

        with Logger(tool) as logger:
            logger.add(Meas.THROUGHPUT, "Read throughput", Aggr.MEAN,
                       kbyte2mbit(rep.read.bandwidth.mean), Mult.MEBI)
            logger.add(Meas.IOPS, "Read iops", Aggr.MEAN,
                       rep.read.iops.mean, Mult.PLAIN)
            logger.add(Meas.LATENCY, "Read clat 99.00 percentile",
                       Aggr.PERCENTILE,
                       rep.read.clatency.percentiles.p99_00 / 1000.0,
                       Mult.MICRO)
            logger.add(Meas.THROUGHPUT, "Write throughput", Aggr.MEAN,
                       kbyte2mbit(rep.write.bandwidth.mean), Mult.MEBI)
            logger.add(Meas.IOPS, "Write iops", Aggr.MEAN,
                       rep.write.iops.mean, Mult.PLAIN)
            logger.add(Meas.LATENCY, "Write clat 99.00 percentile",
                       Aggr.PERCENTILE,
                       rep.write.clatency.percentiles.p99_00 / 1000.0,
                       Mult.MICRO)

    def close(self) -> None:
        """Stop fio (errors tolerated) and destroy the job (idempotent)."""
        if self._closed:
            return
        self._closed = True
        from pyte.errors import TeError
        try:
            self._job.stop()
        except TeError:
            pass
        self._job.destroy()


@contextmanager
def run(pco: "RpcServer", opts: Opts):
    """Context manager: create, start, and clean up a fio job.

    Yields a :class:`Fio` object; call :meth:`Fio.wait` inside the
    block to collect the report.  :meth:`Fio.close` is called on exit.

    Example::

        with fio.run(pco, opts) as f:
            rep = f.wait(timeout=60.0)
            print(rep.read.iops.mean)
    """
    job = pco.job("fio", opts.to_argv())
    try:
        # Attach a readable stdout filter for JSON collection.
        # fio writes the JSON report to stdout; stderr carries human-readable
        # progress and is forwarded to the TE log unread.  (C's fio_internal.c
        # reads stderr and logs stdout; pyte inverts this because the JSON
        # output arrives on stdout, not stderr.)
        stdout_filter = job.stdout.attach_filter(
            name="fio_stdout", readable=True)
        job.stderr.log(level="ERROR")
        job.start()
    except Exception:
        job.destroy()
        raise
    fio_obj = Fio(job, stdout_filter)
    try:
        yield fio_obj
    finally:
        fio_obj.close()
